### ISSUE TITLE
Requesting for GPT Dev Socials.

### ISSUE THREAD

**Issue by charann29** [AINativeLab/gptstore-data-backup#3]
Hello, I am currently assembling a **Discord community dedicated to GPT developers**. Could you kindly help me in identifying and connecting with the social media accounts of GPT developers for our community? Else, if you already have a community, I would be more than happy to join that rather than starting from scratch.

**Comment by airyland** [comment]
Hello! At the moment, we don't have a community set up. However, if you need assistance with GPTs data, I'm here to help. Could you please provide me with more details about the data you're looking for?

**Comment by charann29** [comment]
Hey @Airyland , would be great if you can help me socials of gpt devs for inviting them to our discord server.
I am the one who raised issue in your git repo

**Comment by charann29** [comment]
Hey @Airyland , would be great if you can help me socials of gpt devs for inviting them to our discord server.
